# This file defines all the routes used on the application
# The parameters are:
# path: the url of the route
# controller: The controller to call to handle this route
# action : The function to call inside the specified controller
# requirements (optional): dictionary of constrains for the url parameters ( format: <name of parameter>: <regex constraint> )
#

default:
  path: /
  controller: DefaultController
  action: home

home:
  path: /home
  controller: DefaultController
  action: home

login:
  path: /login
  controller: LoginController
  action: login

logout:
  path: /logout
  controller: LoginController
  action: logout

add_user:
  path: /user/add
  controller: UserController
  action: add

user_verify_email:
  path: /user/verify/email/{email}
  controller: UserController
  action: emailVerify
  requirements:
    email: '[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/'

user_verify_alias:
  path: /user/verify/alias/{alias}
  controller: UserController
  action: aliasVerify
  requirements:
    alias: '[a-zA-Z]+'

user_recipe_list:
  path: /user/view/recipe-list
  controller: UserController
  action: viewRecipe

user_favorite_list:
  path: /user/view/favorite-list
  controller: UserController
  action: viewFavorite

user_mail_confirm:
  path: /user/email/confirmation/{key}
  controller: UserController
  action: emailConfirmation
  requirements:
    key: '[a-zA-Z0-9]{30}'

add_recipe:
  path: /recipe/add
  controller: RecipeController
  action: add

validate_recipe:
  path: /recipe/validate/{id}
  controller: RecipeController
  action: validate
  requirements:
    id: '[0-9]+'

recipe_summary:
  path: /recipe/summary/{id}
  controller: RecipeController
  action: summary
  requirements:
    id: '[0-9]+'

recipe_view:
  path: /recipe/view/{id}
  controller: RecipeController
  action: view
  requirements:
    id: '[0-9]+'

admin_dashboard:
  path: /admin/view/dashboard
  controller: AdminController
  action: view

admin_recipes:
  path: /admin/view/recipes
  controller: AdminController
  action: viewRecipes

admin_tags:
  path: /admin/view/tags
  controller: AdminController
  action: viewTags

admin_allergies:
  path: /admin/view/allergies
  controller: AdminController
  action: viewAllergies

add_allergen:
  path: /allergen/add
  controller: AllergenController
  action: add

delete_allergen:
  path: /allergen/delete/{id}
  controller: AllergenController
  action: delete
  requirements:
    id: '[0-9]+'

add_tag:
  path: /tag/add
  controller: TagController
  action: add

delete_tag:
  path: /tag/delete/{id}
  controller: TagController
  action: delete
  requirements:
    id: '[0-9]+'

task_user_delete:
  path: /task/user/delete
  controller: TaskController
  action: deleteUnvalidUsers
